
services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"  # Maps container port 8000 to host port 8000
    volumes:
      - .:/myapp       # Mounts the current directory to the container's working directory
      - ./db.sqlite3:/myapp/db.sqlite3  # Ensures database persistence
    command: python manage.py runserver 0.0.0.0:8000
